/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.majorproject.gui;

import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import com.itextpdf.text.Document;
import com.itextpdf.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfTable;
import com.mycompany.majorproject.dao.LedgerDAO;
import com.mycompany.majorproject.dao.ProductDAO;
import com.mycompany.majorproject.db.MYSQLConnection;
import com.mycompany.majorproject.pojo.Ledger;
import com.mycompany.majorproject.pojo.Product;
import java.awt.CardLayout;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.IOException;
import javax.mail.PasswordAuthentication;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDPage;

/**
 *
 * @author Nikita
 */
public class MainScreen extends javax.swing.JFrame {

    private CardLayout cl;
    private List<Product> cartData = new ArrayList<>();
    private int cartCount = 0;
    private double totalAmt = 0.0;

    public MainScreen() {

        initComponents();
        super.setLocationRelativeTo(null);
        cl = (CardLayout) cardPanel.getLayout();
        cl.show(cardPanel, "cardAdmin");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cardPanel = new javax.swing.JPanel();
        admin = new javax.swing.JPanel();
        btnOrderHistroy = new javax.swing.JLabel();
        btnPlaceOrder = new javax.swing.JLabel();
        bgAdmin = new javax.swing.JLabel();
        ledger = new javax.swing.JPanel();
        btnBackLedger = new javax.swing.JLabel();
        btnPrintLedger = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableLedger = new javax.swing.JTable();
        bgLedger = new javax.swing.JLabel();
        menuHome = new javax.swing.JPanel();
        btnCountHome = new javax.swing.JLabel();
        btnViewAllVegPizza = new javax.swing.JLabel();
        btnViewAllBeverages = new javax.swing.JLabel();
        btnViewAllNonVegPizza2 = new javax.swing.JLabel();
        btnViewAllPizzaMania = new javax.swing.JLabel();
        btnBagHome = new javax.swing.JLabel();
        btnBackHome = new javax.swing.JLabel();
        bgMenuHome = new javax.swing.JLabel();
        menuVeg = new javax.swing.JPanel();
        v07 = new javax.swing.JLabel();
        btnCountVeg = new javax.swing.JLabel();
        v04 = new javax.swing.JLabel();
        v03 = new javax.swing.JLabel();
        v05 = new javax.swing.JLabel();
        v08 = new javax.swing.JLabel();
        v02 = new javax.swing.JLabel();
        v01 = new javax.swing.JLabel();
        v06 = new javax.swing.JLabel();
        btnBagvegPizza = new javax.swing.JLabel();
        btnBackVegMenu = new javax.swing.JLabel();
        bgMenuVeg = new javax.swing.JLabel();
        menuNonVeg = new javax.swing.JPanel();
        btnBackNonVeg = new javax.swing.JLabel();
        btnCountNonVeg = new javax.swing.JLabel();
        nv04 = new javax.swing.JLabel();
        nv03 = new javax.swing.JLabel();
        nv05 = new javax.swing.JLabel();
        nv08 = new javax.swing.JLabel();
        nv02 = new javax.swing.JLabel();
        nv01 = new javax.swing.JLabel();
        btnBagNonVeg = new javax.swing.JLabel();
        nv06 = new javax.swing.JLabel();
        nv07 = new javax.swing.JLabel();
        bgmenuNonVeg = new javax.swing.JLabel();
        menuManiaVeg = new javax.swing.JPanel();
        btnBackManiaVeg = new javax.swing.JLabel();
        mv05 = new javax.swing.JLabel();
        btnBagManiaVeg = new javax.swing.JLabel();
        mv02 = new javax.swing.JLabel();
        mv04 = new javax.swing.JLabel();
        mv08 = new javax.swing.JLabel();
        mv03 = new javax.swing.JLabel();
        btnCountManiaVeg = new javax.swing.JLabel();
        mv07 = new javax.swing.JLabel();
        mv06 = new javax.swing.JLabel();
        btnPizzaManiaVeg1 = new javax.swing.JLabel();
        btnPizzaManiaNonVeg2 = new javax.swing.JLabel();
        mv01 = new javax.swing.JLabel();
        bgManiaVeg = new javax.swing.JLabel();
        menuManiaNonVeg = new javax.swing.JPanel();
        btnBagManiaNonVeg = new javax.swing.JLabel();
        btnPizzaManiaVeg = new javax.swing.JLabel();
        btnPizzaManiaNonVeg = new javax.swing.JLabel();
        mnv03 = new javax.swing.JLabel();
        btnCountManiaNonVeg = new javax.swing.JLabel();
        mnv01 = new javax.swing.JLabel();
        mnv02 = new javax.swing.JLabel();
        btnBackManiaNonVeg = new javax.swing.JLabel();
        bgManiaNonVeg = new javax.swing.JLabel();
        menuBevarages = new javax.swing.JPanel();
        btnBagBeverage = new javax.swing.JLabel();
        b05 = new javax.swing.JLabel();
        b01 = new javax.swing.JLabel();
        b02 = new javax.swing.JLabel();
        b03 = new javax.swing.JLabel();
        b07 = new javax.swing.JLabel();
        btnCountbevarage = new javax.swing.JLabel();
        b04 = new javax.swing.JLabel();
        b06 = new javax.swing.JLabel();
        btnBackBevarages = new javax.swing.JLabel();
        bgMenuBeverages = new javax.swing.JLabel();
        cart = new javax.swing.JPanel();
        btnBackCart = new javax.swing.JLabel();
        btnRemove = new javax.swing.JLabel();
        btnProceed = new javax.swing.JLabel();
        btnCartCount = new javax.swing.JLabel();
        lblTotalCart = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableCart = new javax.swing.JTable();
        btnBagCart = new javax.swing.JLabel();
        bgCart = new javax.swing.JLabel();
        payment = new javax.swing.JPanel();
        btnBackPayment = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        lblAmountPayable = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        lblGst = new javax.swing.JLabel();
        lblPaymentTotal = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblOrderNumber = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        btnPdfDownload = new javax.swing.JButton();
        btnSendReceipt = new javax.swing.JLabel();
        bgPayment = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1024, 768));
        getContentPane().setLayout(new java.awt.CardLayout());

        cardPanel.setMaximumSize(new java.awt.Dimension(1024, 768));
        cardPanel.setMinimumSize(new java.awt.Dimension(1024, 768));
        cardPanel.setPreferredSize(new java.awt.Dimension(1024, 768));
        cardPanel.setLayout(new java.awt.CardLayout());

        admin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnOrderHistroy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnOrderHistory.png"))); // NOI18N
        btnOrderHistroy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnOrderHistroyMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnOrderHistroyMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnOrderHistroyMouseReleased(evt);
            }
        });
        admin.add(btnOrderHistroy, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 530, -1, -1));

        btnPlaceOrder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnPlaceOrder.png"))); // NOI18N
        btnPlaceOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPlaceOrderMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnPlaceOrderMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnPlaceOrderMouseReleased(evt);
            }
        });
        admin.add(btnPlaceOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 410, -1, -1));

        bgAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/admin.png"))); // NOI18N
        admin.add(bgAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -40, 1100, 850));

        cardPanel.add(admin, "cardAdmin");

        ledger.setPreferredSize(new java.awt.Dimension(1024, 768));
        ledger.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBackLedger.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnBack.png"))); // NOI18N
        btnBackLedger.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackLedgerMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnBackLedgerMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnBackLedgerMouseReleased(evt);
            }
        });
        ledger.add(btnBackLedger, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, 40));

        btnPrintLedger.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnPrintLedger.png"))); // NOI18N
        btnPrintLedger.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPrintLedgerMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnPrintLedgerMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnPrintLedgerMouseReleased(evt);
            }
        });
        btnPrintLedger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintLedgerActionPerformed(evt);
            }
        });
        ledger.add(btnPrintLedger, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 630, 160, 50));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane1.setForeground(new java.awt.Color(230, 26, 57));

        tableLedger.setAutoCreateRowSorter(true);
        tableLedger.setBackground(new java.awt.Color(230, 26, 57));
        tableLedger.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tableLedger.setForeground(new java.awt.Color(255, 255, 255));
        tableLedger.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "NAME", "E-MAIL", "AMOUNT", "DATE", "TIME"
            }
        ));
        tableLedger.setGridColor(new java.awt.Color(230, 26, 57));
        tableLedger.setSelectionBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(tableLedger);

        ledger.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 610, 390));

        bgLedger.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/ledger.png"))); // NOI18N
        bgLedger.setText("jLabel1");
        bgLedger.setMaximumSize(new java.awt.Dimension(1024, 768));
        bgLedger.setMinimumSize(new java.awt.Dimension(1024, 768));
        bgLedger.setPreferredSize(new java.awt.Dimension(1024, 768));
        ledger.add(bgLedger, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -2, -1, 770));

        cardPanel.add(ledger, "cardLedger");

        menuHome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCountHome.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnCountHome.setForeground(new java.awt.Color(230, 26, 57));
        btnCountHome.setText("0");
        menuHome.add(btnCountHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 40, 20, 30));

        btnViewAllVegPizza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnViewAll.png"))); // NOI18N
        btnViewAllVegPizza.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnViewAllVegPizzaMouseClicked(evt);
            }
        });
        menuHome.add(btnViewAllVegPizza, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, -1, -1));

        btnViewAllBeverages.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnViewAll.png"))); // NOI18N
        btnViewAllBeverages.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnViewAllBeveragesMouseClicked(evt);
            }
        });
        menuHome.add(btnViewAllBeverages, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 660, -1, -1));

        btnViewAllNonVegPizza2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnViewAll.png"))); // NOI18N
        btnViewAllNonVegPizza2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnViewAllNonVegPizza2MouseClicked(evt);
            }
        });
        menuHome.add(btnViewAllNonVegPizza2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 340, -1, -1));

        btnViewAllPizzaMania.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnViewAll.png"))); // NOI18N
        btnViewAllPizzaMania.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnViewAllPizzaManiaMouseClicked(evt);
            }
        });
        menuHome.add(btnViewAllPizzaMania, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 340, -1, -1));

        btnBagHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnBag.png"))); // NOI18N
        btnBagHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBagHomeMouseClicked(evt);
            }
        });
        menuHome.add(btnBagHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 40, -1, -1));

        btnBackHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnBack.png"))); // NOI18N
        btnBackHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackHomeMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnBackHomeMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnBackHomeMouseReleased(evt);
            }
        });
        menuHome.add(btnBackHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        bgMenuHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/menuHome.png"))); // NOI18N
        menuHome.add(bgMenuHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        cardPanel.add(menuHome, "cardMenuHome");

        menuVeg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        v07.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnAdd.png"))); // NOI18N
        v07.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                v07MouseClicked(evt);
            }
        });
        menuVeg.add(v07, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 540, -1, -1));

        btnCountVeg.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnCountVeg.setForeground(new java.awt.Color(230, 26, 57));
        btnCountVeg.setText("0");
        menuVeg.add(btnCountVeg, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 20, 20, 30));

        v04.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnAdd.png"))); // NOI18N
        v04.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                v04MouseClicked(evt);
            }
        });
        menuVeg.add(v04, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 710, -1, -1));

        v03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnAdd.png"))); // NOI18N
        v03.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                v03MouseClicked(evt);
            }
        });
        menuVeg.add(v03, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 540, -1, -1));

        v05.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnAdd.png"))); // NOI18N
        v05.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                v05MouseClicked(evt);
            }
        });
        menuVeg.add(v05, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 200, -1, -1));

        v08.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnAdd.png"))); // NOI18N
        v08.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                v08MouseClicked(evt);
            }
        });
        menuVeg.add(v08, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 710, -1, -1));

        v02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnAdd.png"))); // NOI18N
        v02.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                v02MouseClicked(evt);
            }
        });
        menuVeg.add(v02, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, -1, -1));

        v01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnAdd.png"))); // NOI18N
        v01.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                v01MouseClicked(evt);
            }
        });
        menuVeg.add(v01, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, -1, -1));

        v06.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnAdd.png"))); // NOI18N
        v06.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                v06MouseClicked(evt);
            }
        });
        menuVeg.add(v06, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 370, -1, -1));

        btnBagvegPizza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnBag.png"))); // NOI18N
        btnBagvegPizza.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBagvegPizzaMouseClicked(evt);
            }
        });
        menuVeg.add(btnBagvegPizza, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 20, -1, -1));

        btnBackVegMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnBack.png"))); // NOI18N
        btnBackVegMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackVegMenuMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnBackVegMenuMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnBackVegMenuMouseReleased(evt);
            }
        });
        menuVeg.add(btnBackVegMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        bgMenuVeg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/menuVeg.png"))); // NOI18N
        menuVeg.add(bgMenuVeg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        cardPanel.add(menuVeg, "cardMenuVeg");

        menuNonVeg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBackNonVeg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnBack.png"))); // NOI18N
        btnBackNonVeg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackNonVegMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnBackNonVegMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnBackNonVegMouseReleased(evt);
            }
        });
        menuNonVeg.add(btnBackNonVeg, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        btnCountNonVeg.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnCountNonVeg.setForeground(new java.awt.Color(230, 26, 57));
        btnCountNonVeg.setText("0");
        menuNonVeg.add(btnCountNonVeg, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 20, 20, 30));

        nv04.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnAdd.png"))); // NOI18N
        nv04.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nv04MouseClicked(evt);
            }
        });
        menuNonVeg.add(nv04, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 700, -1, -1));

        nv03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnAdd.png"))); // NOI18N
        nv03.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nv03MouseClicked(evt);
            }
        });
        menuNonVeg.add(nv03, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 540, -1, -1));

        nv05.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnAdd.png"))); // NOI18N
        nv05.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nv05MouseClicked(evt);
            }
        });
        menuNonVeg.add(nv05, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 200, -1, -1));

        nv08.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnAdd.png"))); // NOI18N
        nv08.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nv08MouseClicked(evt);
            }
        });
        menuNonVeg.add(nv08, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 700, -1, -1));

        nv02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnAdd.png"))); // NOI18N
        nv02.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nv02MouseClicked(evt);
            }
        });
        menuNonVeg.add(nv02, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, -1, -1));

        nv01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnAdd.png"))); // NOI18N
        nv01.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nv01MouseClicked(evt);
            }
        });
        menuNonVeg.add(nv01, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, -1, -1));

        btnBagNonVeg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnBag.png"))); // NOI18N
        btnBagNonVeg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBagNonVegMouseClicked(evt);
            }
        });
        menuNonVeg.add(btnBagNonVeg, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 20, -1, -1));

        nv06.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnAdd.png"))); // NOI18N
        nv06.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nv06MouseClicked(evt);
            }
        });
        menuNonVeg.add(nv06, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 370, -1, -1));

        nv07.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnAdd.png"))); // NOI18N
        nv07.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nv07MouseClicked(evt);
            }
        });
        menuNonVeg.add(nv07, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 530, -1, -1));

        bgmenuNonVeg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/menuNonVeg.png"))); // NOI18N
        menuNonVeg.add(bgmenuNonVeg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        cardPanel.add(menuNonVeg, "cardMenuNonVeg");

        menuManiaVeg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBackManiaVeg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnBack.png"))); // NOI18N
        btnBackManiaVeg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackManiaVegMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnBackManiaVegMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnBackManiaVegMouseReleased(evt);
            }
        });
        menuManiaVeg.add(btnBackManiaVeg, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        mv05.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnAdd.png"))); // NOI18N
        mv05.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mv05MouseClicked(evt);
            }
        });
        menuManiaVeg.add(mv05, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 210, -1, -1));

        btnBagManiaVeg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnBag.png"))); // NOI18N
        btnBagManiaVeg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBagManiaVegMouseClicked(evt);
            }
        });
        menuManiaVeg.add(btnBagManiaVeg, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 10, -1, -1));

        mv02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnAdd.png"))); // NOI18N
        mv02.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mv02MouseClicked(evt);
            }
        });
        menuManiaVeg.add(mv02, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, -1, -1));

        mv04.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnAdd.png"))); // NOI18N
        mv04.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mv04MouseClicked(evt);
            }
        });
        menuManiaVeg.add(mv04, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 700, -1, -1));

        mv08.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnAdd.png"))); // NOI18N
        mv08.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mv08MouseClicked(evt);
            }
        });
        menuManiaVeg.add(mv08, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 710, -1, -1));

        mv03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnAdd.png"))); // NOI18N
        mv03.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mv03MouseClicked(evt);
            }
        });
        menuManiaVeg.add(mv03, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 530, -1, -1));

        btnCountManiaVeg.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnCountManiaVeg.setForeground(new java.awt.Color(230, 26, 57));
        btnCountManiaVeg.setText("0");
        menuManiaVeg.add(btnCountManiaVeg, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 10, 20, 30));

        mv07.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnAdd.png"))); // NOI18N
        mv07.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mv07MouseClicked(evt);
            }
        });
        menuManiaVeg.add(mv07, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 540, -1, -1));

        mv06.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnAdd.png"))); // NOI18N
        mv06.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mv06MouseClicked(evt);
            }
        });
        menuManiaVeg.add(mv06, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 370, -1, -1));

        btnPizzaManiaVeg1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/txtPizzaManiaVegPressed.png"))); // NOI18N
        btnPizzaManiaVeg1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnPizzaManiaVeg1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnPizzaManiaVeg1MouseReleased(evt);
            }
        });
        menuManiaVeg.add(btnPizzaManiaVeg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, -1, -1));

        btnPizzaManiaNonVeg2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/txtPizzaManiaNonVeg.png"))); // NOI18N
        btnPizzaManiaNonVeg2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPizzaManiaNonVeg2MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnPizzaManiaNonVeg2MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnPizzaManiaNonVeg2MouseReleased(evt);
            }
        });
        menuManiaVeg.add(btnPizzaManiaNonVeg2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 50, -1, -1));

        mv01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnAdd.png"))); // NOI18N
        mv01.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mv01MouseClicked(evt);
            }
        });
        menuManiaVeg.add(mv01, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, -1, -1));

        bgManiaVeg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/menuManiaVeg.png"))); // NOI18N
        menuManiaVeg.add(bgManiaVeg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        cardPanel.add(menuManiaVeg, "cardMenuManiaVeg");

        menuManiaNonVeg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBagManiaNonVeg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnBag.png"))); // NOI18N
        btnBagManiaNonVeg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBagManiaNonVegMouseClicked(evt);
            }
        });
        menuManiaNonVeg.add(btnBagManiaNonVeg, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 10, -1, -1));
        btnBagManiaNonVeg.getAccessibleContext().setAccessibleName("btnBagManiaNonVeg");

        btnPizzaManiaVeg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/txtPizzaManiaVeg.png"))); // NOI18N
        btnPizzaManiaVeg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPizzaManiaVegMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnPizzaManiaVegMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnPizzaManiaVegMouseReleased(evt);
            }
        });
        menuManiaNonVeg.add(btnPizzaManiaVeg, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, -1, -1));

        btnPizzaManiaNonVeg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/txtPizzaManiaNonVegPressed.png"))); // NOI18N
        btnPizzaManiaNonVeg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnPizzaManiaNonVegMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnPizzaManiaNonVegMouseReleased(evt);
            }
        });
        menuManiaNonVeg.add(btnPizzaManiaNonVeg, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 50, -1, -1));

        mnv03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnAdd.png"))); // NOI18N
        mnv03.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnv03MouseClicked(evt);
            }
        });
        menuManiaNonVeg.add(mnv03, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 530, -1, -1));

        btnCountManiaNonVeg.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnCountManiaNonVeg.setForeground(new java.awt.Color(230, 26, 57));
        btnCountManiaNonVeg.setText("0");
        menuManiaNonVeg.add(btnCountManiaNonVeg, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 10, 20, 30));

        mnv01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnAdd.png"))); // NOI18N
        mnv01.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnv01MouseClicked(evt);
            }
        });
        menuManiaNonVeg.add(mnv01, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, -1, -1));

        mnv02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnAdd.png"))); // NOI18N
        mnv02.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnv02MouseClicked(evt);
            }
        });
        menuManiaNonVeg.add(mnv02, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, -1, -1));

        btnBackManiaNonVeg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnBack.png"))); // NOI18N
        btnBackManiaNonVeg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackManiaNonVegMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnBackManiaNonVegMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnBackManiaNonVegMouseReleased(evt);
            }
        });
        menuManiaNonVeg.add(btnBackManiaNonVeg, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        bgManiaNonVeg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/menuManiaNonVeg.png"))); // NOI18N
        menuManiaNonVeg.add(bgManiaNonVeg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        cardPanel.add(menuManiaNonVeg, "cardMenuManiaNonVeg");

        menuBevarages.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBagBeverage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnBag.png"))); // NOI18N
        btnBagBeverage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBagBeverageMouseClicked(evt);
            }
        });
        menuBevarages.add(btnBagBeverage, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 20, -1, -1));

        b05.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnAdd.png"))); // NOI18N
        b05.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b05MouseClicked(evt);
            }
        });
        menuBevarages.add(b05, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 190, -1, -1));

        b01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnAdd.png"))); // NOI18N
        b01.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b01MouseClicked(evt);
            }
        });
        menuBevarages.add(b01, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, -1, -1));

        b02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnAdd.png"))); // NOI18N
        b02.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b02MouseClicked(evt);
            }
        });
        menuBevarages.add(b02, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, -1, -1));

        b03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnAdd.png"))); // NOI18N
        b03.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b03MouseClicked(evt);
            }
        });
        menuBevarages.add(b03, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 520, -1, -1));

        b07.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnAdd.png"))); // NOI18N
        b07.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b07MouseClicked(evt);
            }
        });
        menuBevarages.add(b07, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 520, -1, -1));

        btnCountbevarage.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnCountbevarage.setForeground(new java.awt.Color(230, 26, 57));
        btnCountbevarage.setText("0");
        menuBevarages.add(btnCountbevarage, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 20, 20, 30));

        b04.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnAdd.png"))); // NOI18N
        b04.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b04MouseClicked(evt);
            }
        });
        menuBevarages.add(b04, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 660, -1, -1));

        b06.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnAdd.png"))); // NOI18N
        b06.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b06MouseClicked(evt);
            }
        });
        menuBevarages.add(b06, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 350, -1, -1));

        btnBackBevarages.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnBack.png"))); // NOI18N
        btnBackBevarages.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackBevaragesMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnBackBevaragesMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnBackBevaragesMouseReleased(evt);
            }
        });
        menuBevarages.add(btnBackBevarages, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        bgMenuBeverages.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/menuBeverages.png"))); // NOI18N
        menuBevarages.add(bgMenuBeverages, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        cardPanel.add(menuBevarages, "cardMenuBevarage");

        cart.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBackCart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnBack.png"))); // NOI18N
        btnBackCart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackCartMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnBackCartMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnBackCartMouseReleased(evt);
            }
        });
        cart.add(btnBackCart, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        btnRemove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnRemove.png"))); // NOI18N
        btnRemove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRemoveMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnRemoveMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnRemoveMouseReleased(evt);
            }
        });
        cart.add(btnRemove, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 540, -1, -1));

        btnProceed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnProceed.png"))); // NOI18N
        btnProceed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnProceedMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnProceedMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnProceedMouseReleased(evt);
            }
        });
        cart.add(btnProceed, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 620, -1, -1));

        btnCartCount.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnCartCount.setForeground(new java.awt.Color(230, 26, 57));
        btnCartCount.setText("0");
        cart.add(btnCartCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 20, 20, 30));

        lblTotalCart.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblTotalCart.setText("lbl");
        cart.add(lblTotalCart, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 630, 120, 30));

        tableCart.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "PRODUCT", "AMOUNT"
            }
        ));
        jScrollPane2.setViewportView(tableCart);

        cart.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 510, 320));

        btnBagCart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnBag.png"))); // NOI18N
        cart.add(btnBagCart, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 20, -1, -1));

        bgCart.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bgCart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cart.png"))); // NOI18N
        cart.add(bgCart, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        cardPanel.add(cart, "cardCart");

        payment.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBackPayment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnBack.png"))); // NOI18N
        btnBackPayment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackPaymentMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnBackPaymentMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnBackPaymentMouseReleased(evt);
            }
        });
        payment.add(btnBackPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        lblTime.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        payment.add(lblTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 230, 130, 20));

        lblAmountPayable.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        payment.add(lblAmountPayable, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 510, 180, 20));

        lblDate.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        payment.add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 200, 140, 20));

        lblGst.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        payment.add(lblGst, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 470, 190, 20));

        lblPaymentTotal.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        payment.add(lblPaymentTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 420, 180, 20));

        txtEmail.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        payment.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 330, 150, -1));

        lblOrderNumber.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        payment.add(lblOrderNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 100, 20));

        txtName.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        payment.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 170, -1));

        btnPdfDownload.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnDownloadReceipt.png"))); // NOI18N
        btnPdfDownload.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPdfDownloadMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnPdfDownloadMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnPdfDownloadMouseReleased(evt);
            }
        });
        payment.add(btnPdfDownload, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 620, 160, 50));

        btnSendReceipt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnSendReceipt.png"))); // NOI18N
        btnSendReceipt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSendReceiptMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSendReceiptMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnSendReceiptMouseReleased(evt);
            }
        });
        payment.add(btnSendReceipt, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 550, -1, -1));

        bgPayment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/payment.png"))); // NOI18N
        payment.add(bgPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, -1));

        cardPanel.add(payment, "cardPayment");

        getContentPane().add(cardPanel, "card4");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPlaceOrderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPlaceOrderMousePressed
        btnPlaceOrder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnPlaceOrderPressed.png"))); // NOI18N
    }//GEN-LAST:event_btnPlaceOrderMousePressed

    private void btnPlaceOrderMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPlaceOrderMouseReleased
        btnPlaceOrder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnPlaceOrder.png"))); // NOI18N
    }//GEN-LAST:event_btnPlaceOrderMouseReleased

    private void btnOrderHistroyMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOrderHistroyMousePressed
        btnOrderHistroy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnOrderHistoryPressed.png"))); // NOI18N
    }//GEN-LAST:event_btnOrderHistroyMousePressed

    private void btnOrderHistroyMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOrderHistroyMouseReleased
        btnOrderHistroy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnOrderHistory.png"))); // NOI18N
    }//GEN-LAST:event_btnOrderHistroyMouseReleased

    private void btnBackLedgerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackLedgerMousePressed
        btnBackLedger.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnBackPressed.png"))); // NOI18N
    }//GEN-LAST:event_btnBackLedgerMousePressed

    private void btnBackLedgerMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackLedgerMouseReleased
        btnBackLedger.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnBack.png"))); // NOI18N
    }//GEN-LAST:event_btnBackLedgerMouseReleased

    private void btnOrderHistroyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOrderHistroyMouseClicked
        cl.show(cardPanel, "cardLedger");
        List<Ledger> data = new ArrayList<>();
        try {
            data = LedgerDAO.getAllRecords();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        DefaultTableModel model = (DefaultTableModel) tableLedger.getModel();
        for (int i = model.getRowCount() - 1; i >= 0; i--) {
            model.removeRow(i);
        }
        Object[] row = new Object[6];
        for (Ledger ledger : data) {
            row[0] = ledger.getId();
            row[1] = ledger.getName();
            row[2] = ledger.getEmail();
            row[3] = ledger.getAmount();
            Date d = ledger.getSchedule();
            SimpleDateFormat sl = new SimpleDateFormat("dd-MM-yyyy");
            row[4] = sl.format(d);
            SimpleDateFormat sl2 = new SimpleDateFormat("HH:mm:ss");
            row[5] = sl2.format(d);
            model.addRow(row);
        }

    }//GEN-LAST:event_btnOrderHistroyMouseClicked

    private void btnBackLedgerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackLedgerMouseClicked
        cl.show(cardPanel, "cardAdmin");
    }//GEN-LAST:event_btnBackLedgerMouseClicked

    private void btnBackHomeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackHomeMousePressed
        btnBackHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnBackPressed.png"))); // NOI18N
    }//GEN-LAST:event_btnBackHomeMousePressed

    private void btnBackHomeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackHomeMouseReleased
        btnBackHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnBack.png"))); // NOI18N
    }//GEN-LAST:event_btnBackHomeMouseReleased

    private void btnBackVegMenuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackVegMenuMousePressed
        btnBackVegMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnBackPressed.png"))); // NOI18N
    }//GEN-LAST:event_btnBackVegMenuMousePressed

    private void btnBackVegMenuMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackVegMenuMouseReleased
        btnBackVegMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnBack.png"))); // NOI18N
    }//GEN-LAST:event_btnBackVegMenuMouseReleased

    private void btnBackNonVegMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackNonVegMousePressed
        btnBackNonVeg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnBackPressed.png"))); // NOI18N
    }//GEN-LAST:event_btnBackNonVegMousePressed

    private void btnBackNonVegMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackNonVegMouseReleased
        btnBackNonVeg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnBack.png"))); // NOI18N
    }//GEN-LAST:event_btnBackNonVegMouseReleased

    private void btnBackManiaVegMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackManiaVegMousePressed
        btnBackManiaVeg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnBackPressed.png"))); // NOI18N
    }//GEN-LAST:event_btnBackManiaVegMousePressed

    private void btnBackManiaVegMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackManiaVegMouseReleased
        btnBackManiaVeg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnBack.png"))); // NOI18N
    }//GEN-LAST:event_btnBackManiaVegMouseReleased

    private void btnBackBevaragesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackBevaragesMousePressed
        btnBackBevarages.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnBackPressed.png"))); // NOI18N
    }//GEN-LAST:event_btnBackBevaragesMousePressed

    private void btnBackBevaragesMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackBevaragesMouseReleased
        btnBackBevarages.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnBack.png"))); // NOI18N
    }//GEN-LAST:event_btnBackBevaragesMouseReleased

    private void btnBackCartMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackCartMousePressed
        btnBackCart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnBackPressed.png"))); // NOI18N
    }//GEN-LAST:event_btnBackCartMousePressed

    private void btnBackCartMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackCartMouseReleased
        btnBackCart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnBack.png"))); // NOI18N
    }//GEN-LAST:event_btnBackCartMouseReleased

    private void btnBackPaymentMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackPaymentMousePressed
        btnBackPayment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnBackPressed.png"))); // NOI18N
    }//GEN-LAST:event_btnBackPaymentMousePressed

    private void btnBackPaymentMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackPaymentMouseReleased
        btnBackPayment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnBack.png"))); // NOI18N
    }//GEN-LAST:event_btnBackPaymentMouseReleased

    private void btnBackManiaNonVegMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackManiaNonVegMousePressed
        btnBackManiaNonVeg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnBackPressed.png"))); // NOI18N
    }//GEN-LAST:event_btnBackManiaNonVegMousePressed

    private void btnBackManiaNonVegMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackManiaNonVegMouseReleased
        btnBackManiaNonVeg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnBack.png"))); // NOI18N
    }//GEN-LAST:event_btnBackManiaNonVegMouseReleased

    private void btnPizzaManiaVeg1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPizzaManiaVeg1MousePressed
//        btnPizzaManiaVeg1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/txtPizzaManiaVeg.png"))); // NOI18N
    }//GEN-LAST:event_btnPizzaManiaVeg1MousePressed

    private void btnPizzaManiaVeg1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPizzaManiaVeg1MouseReleased
//        btnPizzaManiaVeg1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/txtPizzaManiaVegPressed.png"))); // NOI18N
    }//GEN-LAST:event_btnPizzaManiaVeg1MouseReleased

    private void btnPizzaManiaNonVeg2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPizzaManiaNonVeg2MousePressed
//        btnPizzaManiaNonVeg2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/txtPizzaManiaNonVegPressed.png"))); // NOI18N
    }//GEN-LAST:event_btnPizzaManiaNonVeg2MousePressed

    private void btnPizzaManiaNonVeg2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPizzaManiaNonVeg2MouseReleased
//        btnPizzaManiaNonVeg2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/txtPizzaManiaNonVeg.png"))); // NOI18N
    }//GEN-LAST:event_btnPizzaManiaNonVeg2MouseReleased

    private void btnPizzaManiaVegMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPizzaManiaVegMousePressed
//        btnPizzaManiaVeg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/txtPizzaManiaVegPressed.png"))); // NOI18N
    }//GEN-LAST:event_btnPizzaManiaVegMousePressed

    private void btnPizzaManiaVegMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPizzaManiaVegMouseReleased
//        btnPizzaManiaVeg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/txtPizzaManiaVeg.png"))); // NOI18N
    }//GEN-LAST:event_btnPizzaManiaVegMouseReleased

    private void btnPizzaManiaNonVegMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPizzaManiaNonVegMousePressed
//        btnPizzaManiaNonVeg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/txtPizzaManiaNonVeg.png"))); // NOI18N
    }//GEN-LAST:event_btnPizzaManiaNonVegMousePressed

    private void btnPizzaManiaNonVegMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPizzaManiaNonVegMouseReleased
//        btnPizzaManiaNonVeg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/txtPizzaManiaNonVegPressed.png"))); // NOI18N
    }//GEN-LAST:event_btnPizzaManiaNonVegMouseReleased

    private void btnRemoveMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRemoveMousePressed
        btnRemove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnRemovePressed.png"))); // NOI18N
    }//GEN-LAST:event_btnRemoveMousePressed

    private void btnRemoveMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRemoveMouseReleased
        btnRemove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnRemove.png"))); // NOI18N
    }//GEN-LAST:event_btnRemoveMouseReleased

    private void btnProceedMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProceedMousePressed
        btnProceed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnProceedPressed.png"))); // NOI18N
    }//GEN-LAST:event_btnProceedMousePressed

    private void btnProceedMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProceedMouseReleased
        btnProceed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnProceed.png"))); // NOI18N
    }//GEN-LAST:event_btnProceedMouseReleased

    private void btnSendReceiptMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSendReceiptMousePressed
        btnSendReceipt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnSendReceiptPressed.png"))); // NOI18N
    }//GEN-LAST:event_btnSendReceiptMousePressed

    private void btnSendReceiptMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSendReceiptMouseReleased
        btnSendReceipt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnSendReceipt.png"))); // NOI18N
    }//GEN-LAST:event_btnSendReceiptMouseReleased

    private void btnPlaceOrderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPlaceOrderMouseClicked
        cl.show(cardPanel, "cardMenuHome");
    }//GEN-LAST:event_btnPlaceOrderMouseClicked

    private void btnBackHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackHomeMouseClicked
        cl.show(cardPanel, "cardAdmin");
    }//GEN-LAST:event_btnBackHomeMouseClicked

    private void btnBagHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBagHomeMouseClicked
        cl.show(cardPanel, "cardCart");
        showProductsInCart();

    }//GEN-LAST:event_btnBagHomeMouseClicked

    private void btnViewAllVegPizzaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewAllVegPizzaMouseClicked
        cl.show(cardPanel, "cardMenuVeg");
    }//GEN-LAST:event_btnViewAllVegPizzaMouseClicked

    private void btnViewAllNonVegPizza2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewAllNonVegPizza2MouseClicked
        cl.show(cardPanel, "cardMenuNonVeg");
    }//GEN-LAST:event_btnViewAllNonVegPizza2MouseClicked

    private void btnViewAllPizzaManiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewAllPizzaManiaMouseClicked
        cl.show(cardPanel, "cardMenuManiaVeg");
    }//GEN-LAST:event_btnViewAllPizzaManiaMouseClicked

    private void btnViewAllBeveragesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewAllBeveragesMouseClicked
        cl.show(cardPanel, "cardMenuBevarage");
    }//GEN-LAST:event_btnViewAllBeveragesMouseClicked

    private void btnBagvegPizzaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBagvegPizzaMouseClicked
        cl.show(cardPanel, "cardCart");
        showProductsInCart();

    }//GEN-LAST:event_btnBagvegPizzaMouseClicked

    private void btnBagNonVegMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBagNonVegMouseClicked
        cl.show(cardPanel, "cardCart");
        showProductsInCart();

    }//GEN-LAST:event_btnBagNonVegMouseClicked

    private void btnBagManiaVegMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBagManiaVegMouseClicked
        cl.show(cardPanel, "cardCart");
        showProductsInCart();

    }//GEN-LAST:event_btnBagManiaVegMouseClicked

    private void btnBagManiaNonVegMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBagManiaNonVegMouseClicked
        cl.show(cardPanel, "cardCart");
        showProductsInCart();

    }//GEN-LAST:event_btnBagManiaNonVegMouseClicked

    private void btnBagBeverageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBagBeverageMouseClicked
        cl.show(cardPanel, "cardCart");
        showProductsInCart();
    }//GEN-LAST:event_btnBagBeverageMouseClicked

    private void btnBackBevaragesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackBevaragesMouseClicked
        cl.show(cardPanel, "cardMenuHome");
    }//GEN-LAST:event_btnBackBevaragesMouseClicked

    private void btnBackManiaNonVegMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackManiaNonVegMouseClicked
        cl.show(cardPanel, "cardMenuHome");
    }//GEN-LAST:event_btnBackManiaNonVegMouseClicked

    private void btnBackManiaVegMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackManiaVegMouseClicked
        cl.show(cardPanel, "cardMenuHome");
    }//GEN-LAST:event_btnBackManiaVegMouseClicked

    private void btnBackNonVegMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackNonVegMouseClicked
        cl.show(cardPanel, "cardMenuHome");
    }//GEN-LAST:event_btnBackNonVegMouseClicked

    private void btnBackVegMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackVegMenuMouseClicked
        cl.show(cardPanel, "cardMenuHome");
    }//GEN-LAST:event_btnBackVegMenuMouseClicked

    private void btnBackCartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackCartMouseClicked
        cl.show(cardPanel, "cardMenuHome");
    }//GEN-LAST:event_btnBackCartMouseClicked

    private void btnPizzaManiaNonVeg2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPizzaManiaNonVeg2MouseClicked
        cl.show(cardPanel, "cardMenuManiaNonVeg");
        btnPizzaManiaNonVeg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/txtPizzaManiaNonVegPressed.png"))); // NOI18N
        btnPizzaManiaVeg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/txtPizzaManiaVeg.png"))); // NOI18N

    }//GEN-LAST:event_btnPizzaManiaNonVeg2MouseClicked

    private void btnPizzaManiaVegMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPizzaManiaVegMouseClicked
        cl.show(cardPanel, "cardMenuManiaVeg");
        btnPizzaManiaVeg1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/txtPizzaManiaVegPressed.png"))); // NOI18N
        btnPizzaManiaNonVeg2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/txtPizzaManiaNonVeg.png"))); // NOI18N


    }//GEN-LAST:event_btnPizzaManiaVegMouseClicked

    private void btnProceedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProceedMouseClicked
        cl.show(cardPanel, "cardPayment");
        if (cartData.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please add products into the cart");
            cl.show(cardPanel, "cardMenuHome");
        } else {
            lblPaymentTotal.setText(Double.toString(totalAmt));
            lblGst.setText(Double.toString((totalAmt * 5) / 100));
            lblAmountPayable.setText(Double.toString(totalAmt + (totalAmt * 5) / 100));
            Date d = new Date();
            SimpleDateFormat sl = new SimpleDateFormat("dd-MM-yyyy");
            lblDate.setText(sl.format(d));
            SimpleDateFormat sl2 = new SimpleDateFormat("HH:mm:ss");
            lblTime.setText(sl2.format(d));
        }
    }//GEN-LAST:event_btnProceedMouseClicked

    private void btnBackPaymentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackPaymentMouseClicked
        cl.show(cardPanel, "cardCart");
    }//GEN-LAST:event_btnBackPaymentMouseClicked

    private void v01MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_v01MouseClicked
        addProduct("v01");
        cartData.forEach((Product e) -> System.out.println(e.toString()));
    }//GEN-LAST:event_v01MouseClicked

    private void v02MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_v02MouseClicked
        addProduct("v02");
    }//GEN-LAST:event_v02MouseClicked

    private void v03MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_v03MouseClicked
        addProduct("v03");
    }//GEN-LAST:event_v03MouseClicked

    private void v04MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_v04MouseClicked
        addProduct("v04");
    }//GEN-LAST:event_v04MouseClicked

    private void v05MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_v05MouseClicked
        addProduct("v05");
    }//GEN-LAST:event_v05MouseClicked

    private void v06MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_v06MouseClicked
        addProduct("v06");
    }//GEN-LAST:event_v06MouseClicked

    private void v07MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_v07MouseClicked
        addProduct("v07");
    }//GEN-LAST:event_v07MouseClicked

    private void v08MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_v08MouseClicked
        addProduct("v08");
    }//GEN-LAST:event_v08MouseClicked

    private void nv01MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nv01MouseClicked
        addProduct("nv01");
    }//GEN-LAST:event_nv01MouseClicked

    private void nv02MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nv02MouseClicked
        addProduct("nv02");
    }//GEN-LAST:event_nv02MouseClicked

    private void nv03MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nv03MouseClicked
        addProduct("nv03");
    }//GEN-LAST:event_nv03MouseClicked

    private void nv04MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nv04MouseClicked
        addProduct("nv04");
    }//GEN-LAST:event_nv04MouseClicked

    private void nv05MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nv05MouseClicked
        addProduct("nv05");
    }//GEN-LAST:event_nv05MouseClicked

    private void nv06MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nv06MouseClicked
        addProduct("nv06");
    }//GEN-LAST:event_nv06MouseClicked

    private void nv07MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nv07MouseClicked
        addProduct("nv07");
    }//GEN-LAST:event_nv07MouseClicked

    private void nv08MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nv08MouseClicked
        addProduct("nv08");
    }//GEN-LAST:event_nv08MouseClicked

    private void mv01MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mv01MouseClicked
        addProduct("mv01");
    }//GEN-LAST:event_mv01MouseClicked

    private void mv02MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mv02MouseClicked
        addProduct("mv02");
    }//GEN-LAST:event_mv02MouseClicked

    private void mv04MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mv04MouseClicked
        addProduct("mv04");
    }//GEN-LAST:event_mv04MouseClicked

    private void mv03MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mv03MouseClicked
        addProduct("mv03");
    }//GEN-LAST:event_mv03MouseClicked

    private void mv05MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mv05MouseClicked
        addProduct("mv05");
    }//GEN-LAST:event_mv05MouseClicked

    private void mv06MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mv06MouseClicked
        addProduct("mv06");
    }//GEN-LAST:event_mv06MouseClicked

    private void mv07MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mv07MouseClicked
        addProduct("mv07");
    }//GEN-LAST:event_mv07MouseClicked

    private void mv08MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mv08MouseClicked
        addProduct("mv08");
    }//GEN-LAST:event_mv08MouseClicked

    private void mnv01MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnv01MouseClicked
        addProduct("mnv01");
    }//GEN-LAST:event_mnv01MouseClicked

    private void mnv02MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnv02MouseClicked
        addProduct("mnv02");
    }//GEN-LAST:event_mnv02MouseClicked

    private void mnv03MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnv03MouseClicked
        addProduct("mnv03");
    }//GEN-LAST:event_mnv03MouseClicked

    private void b01MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b01MouseClicked
        addProduct("b01");
    }//GEN-LAST:event_b01MouseClicked

    private void b02MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b02MouseClicked
        addProduct("b02");
    }//GEN-LAST:event_b02MouseClicked

    private void b03MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b03MouseClicked
        addProduct("b03");
    }//GEN-LAST:event_b03MouseClicked

    private void b04MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b04MouseClicked
        addProduct("b04");
    }//GEN-LAST:event_b04MouseClicked

    private void b05MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b05MouseClicked
        addProduct("b05");
    }//GEN-LAST:event_b05MouseClicked

    private void b06MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b06MouseClicked
        addProduct("b06");
    }//GEN-LAST:event_b06MouseClicked

    private void b07MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b07MouseClicked
        addProduct("b07");
    }//GEN-LAST:event_b07MouseClicked

    private void btnRemoveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRemoveMouseClicked
        
        int row = tableCart.getSelectedRow();
        cartData.remove(row);
        totalAmt = 0;
        showProductsInCart();

    }//GEN-LAST:event_btnRemoveMouseClicked

    private void btnSendReceiptMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSendReceiptMouseClicked
        if (txtName.getText().isEmpty() || txtEmail.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter the name & email first");
        } else if (!isValidEmailAddress(txtEmail.getText())) {
           JOptionPane.showMessageDialog(null, "please enter a valid email");
                    
            txtName.setText("");
            txtEmail.setText("");
        } else {
            Ledger ledger = new Ledger(0, txtName.getText(), txtEmail.getText(), (totalAmt + (totalAmt * 5) / 100), null);
            try {
                LedgerDAO.saveRecord(ledger);
                sendMail(txtName.getText(), txtEmail.getText(), (totalAmt + (totalAmt * 5) / 100));
                JOptionPane.showMessageDialog(null, "Sent successfully");
//                txtName.setText("");
//                txtEmail.setText("");
//                cl.show(cardPanel, "cardMenuHome");
//                totalAmt = 0.0;
//                cartCount = 0;
//                cartData.clear();
//                setCartCount();
            } catch (SQLException ex) {
                Logger.getLogger(MainScreen.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnSendReceiptMouseClicked

    private void btnPdfDownloadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPdfDownloadMouseClicked
        String path = "";
        JFileChooser j = new JFileChooser();
        j.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int x = j.showSaveDialog(this);
        if (x == JFileChooser.APPROVE_OPTION) {
            path = j.getSelectedFile().getPath();
        }

        Document doc = new Document();
        try {
            PdfWriter.getInstance(doc, new FileOutputStream(path + "Receipt.pdf"));
            doc.open();
            doc.addSubject("Dominos");
            doc.add(new Paragraph("Hello " + txtName.getText() + " your order has been placed successfully. Total payable amount is Rs." + lblAmountPayable.getText()));

        } catch (FileNotFoundException ex) {
            Logger.getLogger(MainScreen.class.getName()).log(Level.SEVERE, null, ex);
        } catch (DocumentException ex) {
            Logger.getLogger(MainScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
        doc.close();
        JOptionPane.showMessageDialog(null, "Saved Sucessfully");
        txtName.setText("");
        txtEmail.setText("");
        cl.show(cardPanel, "cardMenuHome");
        totalAmt = 0.0;
        cartCount = 0;
        cartData.clear();
        setCartCount();

    }//GEN-LAST:event_btnPdfDownloadMouseClicked

    private void btnPrintLedgerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrintLedgerMouseClicked
        String path = "";
        JFileChooser j = new JFileChooser();
        j.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int x = j.showSaveDialog(this);
        if (x == JFileChooser.APPROVE_OPTION) {
            path = j.getSelectedFile().getPath();
        }

        Document doc = new Document();

        try {
            PdfWriter.getInstance(doc, new FileOutputStream(path + "Ledger.pdf"));
            doc.open();
            PdfPTable tbl = new PdfPTable(6);
            tbl.addCell("ID");
            tbl.addCell("NAME");
            tbl.addCell("EMAIL");
            tbl.addCell("AMOUNT");
            tbl.addCell("DATE");
            tbl.addCell("TIME");

            for (int i = 0; i < tableLedger.getRowCount(); i++) {
                String Id = tableLedger.getValueAt(i, 0).toString();
                String Name = tableLedger.getValueAt(i, 1).toString();
                String EMail = tableLedger.getValueAt(i, 2).toString();
                String Amount = tableLedger.getValueAt(i, 3).toString();
                String Date = tableLedger.getValueAt(i, 4).toString();
                String Time = tableLedger.getValueAt(i, 5).toString();

                tbl.addCell(Id);
                tbl.addCell(Name);
                tbl.addCell(EMail);
                tbl.addCell(Amount);
                tbl.addCell(Date);
                tbl.addCell(Time);

            }
            doc.add(tbl);

        } catch (DocumentException ex) {
            Logger.getLogger(MainScreen.class.getName()).log(Level.SEVERE, null, ex);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(MainScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
        doc.close();
        JOptionPane.showMessageDialog(null, "Saved Sucessfully");

    }//GEN-LAST:event_btnPrintLedgerMouseClicked

    private void btnPdfDownloadMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPdfDownloadMousePressed
        btnPdfDownload.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnDownloadReceiptPressed.png"))); // NOI18N
    }//GEN-LAST:event_btnPdfDownloadMousePressed

    private void btnPdfDownloadMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPdfDownloadMouseReleased
        btnPdfDownload.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnDownloadReceipt.png"))); // NOI18N
    }//GEN-LAST:event_btnPdfDownloadMouseReleased

    private void btnPrintLedgerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintLedgerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPrintLedgerActionPerformed

    private void btnPrintLedgerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrintLedgerMousePressed
        btnPrintLedger.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnPrintLedgerPressed.png"))); // NOI18N
    }//GEN-LAST:event_btnPrintLedgerMousePressed

    private void btnPrintLedgerMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrintLedgerMouseReleased
        btnPrintLedger.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnPrintLedger.png"))); // NOI18N
    }//GEN-LAST:event_btnPrintLedgerMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel admin;
    private javax.swing.JLabel b01;
    private javax.swing.JLabel b02;
    private javax.swing.JLabel b03;
    private javax.swing.JLabel b04;
    private javax.swing.JLabel b05;
    private javax.swing.JLabel b06;
    private javax.swing.JLabel b07;
    private javax.swing.JLabel bgAdmin;
    private javax.swing.JLabel bgCart;
    private javax.swing.JLabel bgLedger;
    private javax.swing.JLabel bgManiaNonVeg;
    private javax.swing.JLabel bgManiaVeg;
    private javax.swing.JLabel bgMenuBeverages;
    private javax.swing.JLabel bgMenuHome;
    private javax.swing.JLabel bgMenuVeg;
    private javax.swing.JLabel bgPayment;
    private javax.swing.JLabel bgmenuNonVeg;
    private javax.swing.JLabel btnBackBevarages;
    private javax.swing.JLabel btnBackCart;
    private javax.swing.JLabel btnBackHome;
    private javax.swing.JLabel btnBackLedger;
    private javax.swing.JLabel btnBackManiaNonVeg;
    private javax.swing.JLabel btnBackManiaVeg;
    private javax.swing.JLabel btnBackNonVeg;
    private javax.swing.JLabel btnBackPayment;
    private javax.swing.JLabel btnBackVegMenu;
    private javax.swing.JLabel btnBagBeverage;
    private javax.swing.JLabel btnBagCart;
    private javax.swing.JLabel btnBagHome;
    private javax.swing.JLabel btnBagManiaNonVeg;
    private javax.swing.JLabel btnBagManiaVeg;
    private javax.swing.JLabel btnBagNonVeg;
    private javax.swing.JLabel btnBagvegPizza;
    private javax.swing.JLabel btnCartCount;
    private javax.swing.JLabel btnCountHome;
    private javax.swing.JLabel btnCountManiaNonVeg;
    private javax.swing.JLabel btnCountManiaVeg;
    private javax.swing.JLabel btnCountNonVeg;
    private javax.swing.JLabel btnCountVeg;
    private javax.swing.JLabel btnCountbevarage;
    private javax.swing.JLabel btnOrderHistroy;
    private javax.swing.JButton btnPdfDownload;
    private javax.swing.JLabel btnPizzaManiaNonVeg;
    private javax.swing.JLabel btnPizzaManiaNonVeg2;
    private javax.swing.JLabel btnPizzaManiaVeg;
    private javax.swing.JLabel btnPizzaManiaVeg1;
    private javax.swing.JLabel btnPlaceOrder;
    private javax.swing.JButton btnPrintLedger;
    private javax.swing.JLabel btnProceed;
    private javax.swing.JLabel btnRemove;
    private javax.swing.JLabel btnSendReceipt;
    private javax.swing.JLabel btnViewAllBeverages;
    private javax.swing.JLabel btnViewAllNonVegPizza2;
    private javax.swing.JLabel btnViewAllPizzaMania;
    private javax.swing.JLabel btnViewAllVegPizza;
    private javax.swing.JPanel cardPanel;
    private javax.swing.JPanel cart;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAmountPayable;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblGst;
    private javax.swing.JLabel lblOrderNumber;
    private javax.swing.JLabel lblPaymentTotal;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblTotalCart;
    private javax.swing.JPanel ledger;
    private javax.swing.JPanel menuBevarages;
    private javax.swing.JPanel menuHome;
    private javax.swing.JPanel menuManiaNonVeg;
    private javax.swing.JPanel menuManiaVeg;
    private javax.swing.JPanel menuNonVeg;
    private javax.swing.JPanel menuVeg;
    private javax.swing.JLabel mnv01;
    private javax.swing.JLabel mnv02;
    private javax.swing.JLabel mnv03;
    private javax.swing.JLabel mv01;
    private javax.swing.JLabel mv02;
    private javax.swing.JLabel mv03;
    private javax.swing.JLabel mv04;
    private javax.swing.JLabel mv05;
    private javax.swing.JLabel mv06;
    private javax.swing.JLabel mv07;
    private javax.swing.JLabel mv08;
    private javax.swing.JLabel nv01;
    private javax.swing.JLabel nv02;
    private javax.swing.JLabel nv03;
    private javax.swing.JLabel nv04;
    private javax.swing.JLabel nv05;
    private javax.swing.JLabel nv06;
    private javax.swing.JLabel nv07;
    private javax.swing.JLabel nv08;
    private javax.swing.JPanel payment;
    private javax.swing.JTable tableCart;
    private javax.swing.JTable tableLedger;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtName;
    private javax.swing.JLabel v01;
    private javax.swing.JLabel v02;
    private javax.swing.JLabel v03;
    private javax.swing.JLabel v04;
    private javax.swing.JLabel v05;
    private javax.swing.JLabel v06;
    private javax.swing.JLabel v07;
    private javax.swing.JLabel v08;
    // End of variables declaration//GEN-END:variables
private void addProduct(String prodId) {
        try {
            cartData.add(ProductDAO.findProductByProdId(prodId));
            cartCount = cartData.size();
            setCartCount();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }

    private void setCartCount() {
        btnCountHome.setText(Integer.toString(cartCount));
        btnCountManiaNonVeg.setText(Integer.toString(cartCount));
        btnCountManiaVeg.setText(Integer.toString(cartCount));
        btnCountNonVeg.setText(Integer.toString(cartCount));
        btnCountVeg.setText(Integer.toString(cartCount));
        btnCountbevarage.setText(Integer.toString(cartCount));
        btnCartCount.setText(Integer.toString(cartCount));
    }

    private void showProductsInCart() {
        DefaultTableModel model = (DefaultTableModel) tableCart.getModel();
        for (int i = model.getRowCount() - 1; i >= 0; i--) {
            model.removeRow(i);
        }
        Object[] row = new Object[2];

        for (Product product : cartData) {
            row[0] = product.getProdName();
            row[1] = product.getProdAmt();
            totalAmt += product.getProdAmt();
            model.addRow(row);
        }
        lblTotalCart.setText("₹ " + Double.toString(totalAmt));
    }

    public boolean isValidEmailAddress(String email) {
        String ePattern = "^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@((\\[[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\])|(([a-zA-Z\\-0-9]+\\.)+[a-zA-Z]{2,}))$";
        java.util.regex.Pattern p = java.util.regex.Pattern.compile(ePattern);
        java.util.regex.Matcher m = p.matcher(email);
        return m.matches();
    }

    public static void sendMail(String name, String email, double amount) {
        // Put recipient’s address
        String to = email;
// Put sender’s address
        String from = "kumarinik2331@gmail.com";
//Assuming you are sending email from through gmails smtp
        String host = "smtp.gmail.com";
//get system properties
        Properties props = System.getProperties();
//setup mail server

        props.put("mail.smtp.host", host);
        props.put("mail.smtp.port", "465");
        props.put("mail.smtp.ssl.enable", "true");//it’s optional in Mailtrap 
        props.put("mail.smtp.auth", "true");

//get the session object.//and pass username and password
        Session session = Session.getInstance(props, new javax.mail.Authenticator() {
            protected PasswordAuthentication getPasswordauthentication() {
                return new PasswordAuthentication("kumarinik2331@gmail.com", "BITCHisIN2002700@mafiaHELL");
            }
        });

//used to debug smtp issues
        session.setDebug(true);

        try {
//create a default mimemessaage object
            MimeMessage message = new MimeMessage(session);

//Set from:header field of the header
            message.setFrom(new InternetAddress(from));

// Set To: header field of the header
            message.addRecipient(Message.RecipientType.TO, new InternetAddress(to));

            // Set Subject: header field
            message.setSubject("Dominoes");

            // Put the content of your message
//            message.setText("Hi there, this is my first message sent with JavaMail");
            message.setContent("<h1>Hello " + name + " your order has been placed successfully. Total payable amount is Rs." + amount + "</h1>", "text/html;charset=utf-8");
            System.out.println("sending...");
            // Send message
//            Transport.send(message);
            Transport.send(message, "kumarinik2331@gmail.com", "BITCHisIN2002700@mafiaHELL");

            System.out.println("Sent message successfully....");

        } catch (MessagingException ex) {
            ex.printStackTrace();
        }
    }
}
